python _main_mnist_weightGAN.py --iris --train --wSize 2
python _main_mnist_weightGAN.py --iris --train --wSize 2
python _main_mnist_weightGAN.py --iris --train --wSize 3
python _main_mnist_weightGAN.py --iris --train --wSize 3
python _main_mnist_weightGAN.py --iris --train --wSize 4
python _main_mnist_weightGAN.py --iris --train --wSize 4
python _main_mnist_weightGAN.py --iris --train --wSize 5
python _main_mnist_weightGAN.py --iris --train --wSize 5
python _main_mnist_weightGAN.py --iris --train --wSize 10
python _main_mnist_weightGAN.py --iris --train --wSize 10
python _main_mnist_weightGAN.py --iris --train --wSize 20
python _main_mnist_weightGAN.py --iris --train --wSize 20
python _main_mnist_weightGAN.py --iris --train --wSize 30
python _main_mnist_weightGAN.py --iris --train --wSize 40
python _main_mnist_weightGAN.py --iris --train --wSize 50
python _main_mnist_weightGAN.py --iris --train --wSize 50
python _main_mnist_weightGAN.py --iris --train --wSize 60
python _main_mnist_weightGAN.py --iris --train --wSize 60
python _main_mnist_weightGAN.py --iris --train --wSize 70
python _main_mnist_weightGAN.py --iris --train --wSize 70
python _main_mnist_weightGAN.py --iris --train --wSize 80
python _main_mnist_weightGAN.py --iris --train --wSize 80
python _main_mnist_weightGAN.py --iris --train --wSize 90
python _main_mnist_weightGAN.py --iris --train --wSize 90
python _main_mnist_weightGAN.py --iris --train --wSize 100
python _main_mnist_weightGAN.py --iris --train --wSize 100

python _main_mnist_weightGAN.py --mnist --train --wSize 2
python _main_mnist_weightGAN.py --mnist --train --wSize 2
python _main_mnist_weightGAN.py --mnist --train --wSize 3
python _main_mnist_weightGAN.py --mnist --train --wSize 3
python _main_mnist_weightGAN.py --mnist --train --wSize 4
python _main_mnist_weightGAN.py --mnist --train --wSize 4
python _main_mnist_weightGAN.py --mnist --train --wSize 5
python _main_mnist_weightGAN.py --mnist --train --wSize 5
python _main_mnist_weightGAN.py --mnist --train --wSize 10
python _main_mnist_weightGAN.py --mnist --train --wSize 10
python _main_mnist_weightGAN.py --mnist --train --wSize 20
python _main_mnist_weightGAN.py --mnist --train --wSize 20
python _main_mnist_weightGAN.py --mnist --train --wSize 30
python _main_mnist_weightGAN.py --mnist --train --wSize 40
python _main_mnist_weightGAN.py --mnist --train --wSize 50
python _main_mnist_weightGAN.py --mnist --train --wSize 50
python _main_mnist_weightGAN.py --mnist --train --wSize 60
python _main_mnist_weightGAN.py --mnist --train --wSize 60
python _main_mnist_weightGAN.py --mnist --train --wSize 70
python _main_mnist_weightGAN.py --mnist --train --wSize 70
python _main_mnist_weightGAN.py --mnist --train --wSize 80
python _main_mnist_weightGAN.py --mnist --train --wSize 80
python _main_mnist_weightGAN.py --mnist --train --wSize 90
python _main_mnist_weightGAN.py --mnist --train --wSize 90
python _main_mnist_weightGAN.py --mnist --train --wSize 100
python _main_mnist_weightGAN.py --mnist --train --wSize 100
